spring:
  application:
    name: PSpringUI

management:
  endpoints:
    web:
      exposure:
        include=*:

server:
  port: ${PORT:8080}


---
spring:
  profiles: cloud

uri:
  gateway: http://gateway-99bc92bf-92f4-4969-9eb9-2577de9ee86b.apps.cf.martin-bw-piv.net/api
  registry: http://PSPRINGAPI