spring:
  application:
    name: PSpringUI

management:
  endpoints:
    web:
      exposure:
        include=*:

server:
  port: ${PORT:8080}


---
spring:
  profiles: default

uri:
  registry: http://PSPRINGAPI
  gateway: https://gateway-3d2b7e96-27e3-4448-80d3-82ced06651da.apps.cf.martin-bw-piv.net/api
