spring:
  application:
      name: SpringEureka
      
server:
  port: ${PORT:8761}

---
spring:
  profiles: local

eureka:
  instance:
    hostname: ${spring.cloud.client.hostname}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
        enabled: true
  server:
    enableSelfPreservation: true

---
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
        enabled: true
  server:
    enableSelfPreservation: true
